feat: fastapi + redis sample app
keploy/samples-python pull request #24
Opened 2024-07-22 14:42 UTC by sammaji

2024-07-22 14:44 UTC, sammaji commented
Hi @Sonichigo @Swpn0neel can you please review it?

2024-07-23 05:40 UTC, Sonichigo commented
> Hi @Sonichigo @Swpn0neel can you please review it?

Hey, @sammaji can add a readme file with instructions and curl commands.!

2024-07-23 06:04 UTC, sammaji commented
@Sonichigo there is a readme file with instructions and some curl commands for interacting with the api.

2024-07-23 08:11 UTC, Swpn0neel approved these changes
LGTM! But for further improvement you can add more curl commands to cover all of your operations, and also you can generate the test coverage report using Keploy!

2024-07-29 11:10 UTC, Sonichigo requested changes

2024-07-29 11:10 UTC, Sonichigo commented on flask-redis/README.md
> +curl --location 'http://127.0.0.1:8000/todos/'
this curl command isn't working

2024-07-29 11:10 UTC, Sonichigo commented on flask-redis/README.md
> +curl --location 'http://127.0.0.1:3000/todos/' \
this one throws 400 bad request

2024-07-29 11:10 UTC, Sonichigo commented on flask-redis/README.md
> +## Setup With Docker
this paragraph isn't required

2024-07-29 11:10 UTC, Sonichigo commented on flask-redis/README.md
> +Make sure you have provided all the environment variables in `.env` file.
please add `.env.sample` on what things to add in the file.

2024-07-29 11:10 UTC, Sonichigo commented on flask-redis/README.md
> +### For Linux, MacOS and WSL
You can add one-click installation url and remove line from 49, to 58.

2024-08-08 07:58 UTC, Sonichigo commented
Stale PR. Closing the pr since now it has conflicts as well

2024-08-08 07:58 UTC, closed without merging